---
name: "Integration"
on:  # yamllint disable-line rule:truthy
  pull_request_target:
    branches: [main]

jobs:
  post-results:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Add comment
        uses: mshick/add-pr-comment@v2
        env:
          pr_number: ${{ github.event.pull_request.number }}
        with:
          issue: ${{ env.pr_number }}
          message: |
            Results:
              - Test: OK (#${{ env.pr_number }})
